version: '3'

services:

  schulcloud-client:
    image: schulcloud-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      BACKEND_URL: https://schul-cloud.org:8080/
    ports:
      - 3100:3100
      - 9310:9310
    external_links:
      - schulcloud-server:server
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules/
      - data-schulcloud-client-build:/home/node/app/build/
    command: npm run debug

  schulcloud-client-gulp:
    image: node:8.7.0
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules/
      - data-schulcloud-client-build:/home/node/app/build/
    command: bash -c "npm install -gq gulp && cd /home/node/app && gulp watch"

volumes:
  data-schulcloud-client-build:

#networks:
#  default:
#    external:
#      name: schulcloudserver_schulcloud-server-network